/* registry.js: GENERATED by contrast.py from palettes.json. Do not edit by hand. */
window.BT_REGISTRY = {
 "version": "0.1.0",
 "date": "2026-09-26",
 "styles": {
  "pop": {
   "name": "Pop",
   "blurb": "Vastag körvonal, kemény árnyék, színes blokkok.",
   "sets": [
    "pop-citrom",
    "pop-aperol",
    "pop-matcha",
    "pop-gelato",
    "pop-balaton",
    "pop-ejfel"
   ],
   "fonts": [
    "space-grotesk",
    "bricolage",
    "unbounded",
    "archivo",
    "rubik"
   ],
   "defaultFont": "space-grotesk",
   "pair": {
    "light": "pop-citrom",
    "dark": "pop-ejfel"
   }
  },
  "uveg": {
   "name": "Üveg",
   "blurb": "Mattüveg lapok színes derengés fölött.",
   "sets": [
    "uveg-piac",
    "uveg-aperol",
    "uveg-gelato",
    "uveg-balaton",
    "uveg-matcha",
    "uveg-neon",
    "uveg-paprika"
   ],
   "fonts": [
    "nunito",
    "outfit",
    "sora",
    "jakarta",
    "fraunces"
   ],
   "defaultFont": "nunito",
   "pair": {
    "light": "uveg-piac",
    "dark": "uveg-paprika"
   },
   "glass": {
    "saturate": 1.8,
    "cardFloor": 68,
    "phonebarFloor": 86,
    "tintRange": [
     40,
     85
    ],
    "blurRange": [
     6,
     32
    ]
   }
  },
  "klasszikus": {
   "name": "Klasszikus",
   "blurb": "Nyugodt, vékony vonalak, papírfehér.",
   "sets": [
    "klasszikus-nappal",
    "klasszikus-ejjel"
   ],
   "fonts": [
    "newsreader",
    "sourceserif",
    "playfair",
    "literata"
   ],
   "defaultFont": "newsreader",
   "pair": {
    "light": "klasszikus-nappal",
    "dark": "klasszikus-ejjel"
   }
  }
 },
 "sets": {
  "pop-citrom": {
   "name": "Citrom",
   "slug": "citrom",
   "style": "pop",
   "scheme": "light",
   "swatch": [
    "#ffe500",
    "#2a48f5",
    "#ff2d9b",
    "#ffffff"
   ]
  },
  "pop-aperol": {
   "name": "Aperol",
   "slug": "aperol",
   "style": "pop",
   "scheme": "light",
   "swatch": [
    "#ff7a3d",
    "#b83210",
    "#ff3d81",
    "#fff5ee"
   ]
  },
  "pop-matcha": {
   "name": "Matcha",
   "slug": "matcha",
   "style": "pop",
   "scheme": "light",
   "swatch": [
    "#9be15d",
    "#2f6f16",
    "#ff8a6b",
    "#f5fbee"
   ]
  },
  "pop-gelato": {
   "name": "Gelato",
   "slug": "gelato",
   "style": "pop",
   "scheme": "light",
   "swatch": [
    "#a78bfa",
    "#5b3be8",
    "#ff7aa2",
    "#f8f5ff"
   ]
  },
  "pop-balaton": {
   "name": "Balaton",
   "slug": "balaton",
   "style": "pop",
   "scheme": "light",
   "swatch": [
    "#38d6e0",
    "#0b6e8a",
    "#ff7a6b",
    "#effbfb"
   ]
  },
  "pop-ejfel": {
   "name": "Éjfél",
   "slug": "ejfel",
   "style": "pop",
   "scheme": "dark",
   "swatch": [
    "#ffe500",
    "#ffe500",
    "#ff6b8b",
    "#0a0a0a"
   ]
  },
  "uveg-piac": {
   "name": "Piac",
   "slug": "piac",
   "style": "uveg",
   "scheme": "light",
   "swatch": [
    "#aa2e1a",
    "#ffb347",
    "#ff6b4a",
    "#fff6ea"
   ]
  },
  "uveg-aperol": {
   "name": "Aperol",
   "slug": "aperol",
   "style": "uveg",
   "scheme": "light",
   "swatch": [
    "#943823",
    "#ff7a3d",
    "#ff3d81",
    "#fff1e8"
   ]
  },
  "uveg-gelato": {
   "name": "Gelato",
   "slug": "gelato",
   "style": "uveg",
   "scheme": "light",
   "swatch": [
    "#5b3be8",
    "#a78bfa",
    "#ff8ac0",
    "#f7f5ff"
   ]
  },
  "uveg-balaton": {
   "name": "Balaton",
   "slug": "balaton",
   "style": "uveg",
   "scheme": "light",
   "swatch": [
    "#09687c",
    "#38d6e0",
    "#5b9dff",
    "#eefbfb"
   ]
  },
  "uveg-matcha": {
   "name": "Matcha",
   "slug": "matcha",
   "style": "uveg",
   "scheme": "light",
   "swatch": [
    "#336f1a",
    "#9be15d",
    "#ff8fab",
    "#f4f8ec"
   ]
  },
  "uveg-neon": {
   "name": "Neon",
   "slug": "neon",
   "style": "uveg",
   "scheme": "dark",
   "swatch": [
    "#c6ff3d",
    "#c6ff3d",
    "#ff5cc8",
    "#0f0f14"
   ]
  },
  "uveg-paprika": {
   "name": "Paprika",
   "slug": "paprika",
   "style": "uveg",
   "scheme": "dark",
   "swatch": [
    "#ff7a5c",
    "#ff4d2e",
    "#ffb703",
    "#1a0f14"
   ]
  },
  "klasszikus-nappal": {
   "name": "Klasszikus",
   "slug": "nappal",
   "style": "klasszikus",
   "scheme": "light",
   "swatch": [
    "#0f4c81",
    "#e2e2dd",
    "#ffffff",
    "#f6f6f4"
   ]
  },
  "klasszikus-ejjel": {
   "name": "Klasszikus éjjel",
   "slug": "ejjel",
   "style": "klasszikus",
   "scheme": "dark",
   "swatch": [
    "#8fbcec",
    "#2c2c2a",
    "#1f1f1d",
    "#151514"
   ]
  }
 },
 "fonts": {
  "space-grotesk": {
   "name": "Space Grotesk",
   "style": "pop"
  },
  "bricolage": {
   "name": "Bricolage Grotesque",
   "style": "pop"
  },
  "unbounded": {
   "name": "Unbounded",
   "style": "pop"
  },
  "archivo": {
   "name": "Archivo keskeny",
   "style": "pop"
  },
  "rubik": {
   "name": "Rubik",
   "style": "pop"
  },
  "nunito": {
   "name": "Nunito",
   "style": "uveg"
  },
  "outfit": {
   "name": "Outfit",
   "style": "uveg"
  },
  "sora": {
   "name": "Sora",
   "style": "uveg"
  },
  "jakarta": {
   "name": "Plus Jakarta Sans",
   "style": "uveg"
  },
  "fraunces": {
   "name": "Fraunces",
   "style": "uveg"
  },
  "newsreader": {
   "name": "Newsreader",
   "style": "klasszikus"
  },
  "sourceserif": {
   "name": "Source Serif 4",
   "style": "klasszikus"
  },
  "playfair": {
   "name": "Playfair Display",
   "style": "klasszikus"
  },
  "literata": {
   "name": "Literata",
   "style": "klasszikus"
  }
 },
 "defaults": {
  "style": "pop",
  "colour": "auto",
  "font": "space-grotesk",
  "glass": "chrome",
  "blur": 18,
  "tint": 55
 },
 "labStart": {
  "style": "pop",
  "colour": "citrom",
  "font": "space-grotesk"
 }
};
