/* registry.js: GENERATED by tools/build.py. Do not edit by hand. The Pop colour sets, their
   screen blocks and the Pop fonts, for the lab controls and the Settings card. */
window.BT_REGISTRY = {
 "version": "0.1.0",
 "sets": {
  "pop-citrom": {
   "name": "Citrom",
   "slug": "citrom",
   "scheme": "light",
   "bg": "#ffffff",
   "accent": "#2a48f5",
   "blocks": [
    "#ffe500",
    "#38d6e0",
    "#ff2d9b",
    "#9be15d"
   ],
   "sec": {
    "ma": "#ffe500",
    "rev": "#38d6e0",
    "rep": "#ff2d9b",
    "ins": "#9be15d",
    "set": "#a78bfa",
    "ven": "#ff7a3d",
    "start": "#9be15d"
   }
  },
  "pop-aperol": {
   "name": "Aperol",
   "slug": "aperol",
   "scheme": "light",
   "bg": "#fff5ee",
   "accent": "#b83210",
   "blocks": [
    "#ff7a3d",
    "#ffc24a",
    "#ff3d81",
    "#7ee0b8"
   ],
   "sec": {
    "ma": "#ff7a3d",
    "rev": "#ffc24a",
    "rep": "#ff3d81",
    "ins": "#7ee0b8",
    "set": "#ffb38a",
    "ven": "#b9a6ff",
    "start": "#7ee0b8"
   }
  },
  "pop-matcha": {
   "name": "Matcha",
   "slug": "matcha",
   "scheme": "light",
   "bg": "#f5fbee",
   "accent": "#2f6f16",
   "blocks": [
    "#9be15d",
    "#ffe27a",
    "#ff8fab",
    "#6fdcc4"
   ],
   "sec": {
    "ma": "#9be15d",
    "rev": "#ffe27a",
    "rep": "#ff8fab",
    "ins": "#6fdcc4",
    "set": "#c3b1ff",
    "ven": "#ff8a6b",
    "start": "#ffe27a"
   }
  },
  "pop-gelato": {
   "name": "Gelato",
   "slug": "gelato",
   "scheme": "light",
   "bg": "#f8f5ff",
   "accent": "#5b3be8",
   "blocks": [
    "#a78bfa",
    "#7dd3fc",
    "#ff8ac0",
    "#86efac"
   ],
   "sec": {
    "ma": "#a78bfa",
    "rev": "#7dd3fc",
    "rep": "#ff8ac0",
    "ins": "#86efac",
    "set": "#fde68a",
    "ven": "#ffb38a",
    "start": "#86efac"
   }
  },
  "pop-balaton": {
   "name": "Balaton",
   "slug": "balaton",
   "scheme": "light",
   "bg": "#effbfb",
   "accent": "#0b6e8a",
   "blocks": [
    "#38d6e0",
    "#ffe08a",
    "#ff7a6b",
    "#7ee8b0"
   ],
   "sec": {
    "ma": "#38d6e0",
    "rev": "#ffe08a",
    "rep": "#ff7a6b",
    "ins": "#7ee8b0",
    "set": "#7fb2ff",
    "ven": "#c4b5fd",
    "start": "#7ee8b0"
   }
  },
  "pop-ejfel": {
   "name": "Éjfél",
   "slug": "ejfel",
   "scheme": "dark",
   "bg": "#0a0a0a",
   "accent": "#ffe500",
   "blocks": [
    "#ffe500",
    "#5ee0ea",
    "#ff5cb0",
    "#5fe3a1"
   ],
   "sec": {
    "ma": "#ffe500",
    "rev": "#5ee0ea",
    "rep": "#ff5cb0",
    "ins": "#5fe3a1",
    "set": "#b49cff",
    "ven": "#ff8f5c",
    "start": "#5fe3a1"
   }
  }
 },
 "order": [
  "pop-citrom",
  "pop-aperol",
  "pop-matcha",
  "pop-gelato",
  "pop-balaton",
  "pop-ejfel"
 ],
 "pair": {
  "light": "pop-citrom",
  "dark": "pop-ejfel"
 },
 "fonts": {
  "space-grotesk": {
   "name": "Space Grotesk"
  },
  "bricolage": {
   "name": "Bricolage Grotesque"
  },
  "unbounded": {
   "name": "Unbounded"
  },
  "archivo": {
   "name": "Archivo keskeny"
  },
  "rubik": {
   "name": "Rubik"
  }
 },
 "fontOrder": [
  "space-grotesk",
  "bricolage",
  "unbounded",
  "archivo",
  "rubik"
 ],
 "defaultFont": "space-grotesk",
 "sections": {
  "ma": "Ma",
  "rev": "Értékelések",
  "rep": "Válaszok",
  "ins": "Kimutatások",
  "set": "Beállítások",
  "ven": "Éttermek",
  "start": "Első lépések"
 }
};
